name: Update README with Commit


on:
  push:
    branches:
      - v1.8.5-1.28.4
    paths-ignore:
      - "*.md"      
      
  pull_request:
    branches:
    - v1.8.5-1.28.4
    types: 
      - "closed"
    paths-ignore:
      - "*.md"

      
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update README
        run: |
          echo -e "\n\n" >> README.md
          git log -1 --pretty=format:"$(git rev-parse HEAD) | %an | %s | %ad "  --date=short >> README.md          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updating README with brief commit details"
          git push
